#!/usr/bin/env python3
"""Render compact paper results from the immutable spec-012 CSV handoff.

Run from any directory, with --check to compare all outputs without writing.
No measurements, raw-data downloads, plotting packages, or TeX are required.
The handoff's raw-data rederivation receipts are retained separately; this tool
verifies their compact CSV identities and independently repeats the hierarchical
summary calculation from the committed per-process summaries, not raw callbacks.
"""
# Copyright 2026 Arhythmetic Units
# SPDX-License-Identifier: GPL-3.0-or-later
import argparse
from collections import Counter, defaultdict
import csv
import hashlib
import json
import math
from pathlib import Path
import statistics

PAPER = Path(__file__).resolve().parents[1]
SOURCE = PAPER / "data/comparison-012"
OUTPUT = PAPER / "generated/paper-comparison"
GROUPS = ("primary", "extensions", "short-hop", "single-sample", "transitions")
BASE = dict(n="4096", hop="1024", block="64", state="steady", smooth="0",
            rate="48000", count="1", alignment="aligned", load="0", voices="1",
            cache_mib="0", callback_offset="0")
LABELS = {
    "core-float": "Production core", "legacy-batch-float": "Legacy batch",
    "legacy-incremental-float": "Legacy incremental",
    "pffft-scheduled-batch-float": "PFFFT scheduled batch",
    "pffft-hybrid-float": "PFFFT hybrid", "pffft-analysis-float": "PFFFT native",
    "fftw-analysis-float": "FFTW native", "vdsp-analysis-float": "vDSP native",
}
ANALYSIS = tuple(LABELS)
COMMENT = "% Generated by tools/comparison_paper.py; do not edit.\n"


def digest(data):
    return hashlib.sha256(data).hexdigest()


def close(actual, expected, context):
    if not math.isclose(float(actual), float(expected), rel_tol=2e-12, abs_tol=1e-12):
        raise ValueError(f"Summary mismatch: {context}: {actual} != {expected}")


def sci(value):
    mantissa, exponent = f"{float(value):.2e}".split("e")
    return rf"${mantissa}\times10^{{{int(exponent)}}}$"


def interval(row, value, low, high, places=2):
    return (f"{float(row[value]):.{places}f} "
            f"[{float(row[low]):.{places}f}, {float(row[high]):.{places}f}]")


def table(headers, rows, caption, label, spec):
    return (COMMENT + "\\begin{table}[tb]\n\\centering\\small\n"
            "\\setlength{\\tabcolsep}{4pt}\n"
            + "\\begin{tabular}{@{}" + spec + "@{}}\n\\toprule\n"
            + " & ".join(headers) + " \\\\\n\\midrule\n"
            + "\n".join(" & ".join(r) + " \\\\" for r in rows)
            + "\n\\bottomrule\n\\end{tabular}\n\\caption{" + caption
            + "}\n\\label{" + label + "}\n\\end{table}\n")


class Evidence:
    def __init__(self):
        self.manifest = json.loads((SOURCE / "manifest.json").read_text())
        self.inputs = {"data/comparison-012/manifest.json": digest((SOURCE / "manifest.json").read_bytes())}
        self.selected = {}
        self.data = {}
        csv.field_size_limit(16 * 1024 * 1024)
        for group in GROUPS:
            self.data[group] = {}
            for name in ("results", "process-timings", "accuracy-coverage"):
                self.data[group][name] = self.read(group, name)
        self.validate_summaries()

    def read(self, group, name):
        relative = f"tables/{group}/{name}.csv"
        path = SOURCE / relative
        data = path.read_bytes()
        if digest(data) != self.manifest["files"][relative]:
            raise ValueError(f"Changed immutable handoff input: {relative}")
        self.inputs[str(path.relative_to(PAPER))] = digest(data)
        return list(csv.DictReader(data.decode().splitlines()))

    def read_json(self, name):
        path = SOURCE / name
        data = path.read_bytes()
        if digest(data) != self.manifest["files"][name]:
            raise ValueError(f"Changed immutable handoff input: {name}")
        self.inputs[str(path.relative_to(PAPER))] = digest(data)
        return json.loads(data)

    def validate_summaries(self):
        for group in GROUPS:
            processes = defaultdict(list)
            for row in self.data[group]["process-timings"]:
                processes[row["config_sha256"]].append(row)
            for row in self.data[group]["results"]:
                ident = row["config_sha256"]
                ps = processes[ident]
                if len(ps) != 9 or len({(p["session"], p["repeat"]) for p in ps}) != 9:
                    raise ValueError(f"Not nine distinct process observations: {ident}")
                sessions = defaultdict(list)
                for p in ps:
                    if p["stratum"] != row["stratum"] or p["host"] != row["host"]:
                        raise ValueError(f"Mixed measurement stratum: {ident}")
                    sessions[p["session"]].append(p)
                if len(sessions) != 3 or any(len(v) != 3 for v in sessions.values()):
                    raise ValueError(f"Not three sessions of three processes: {ident}")
                costs = [statistics.mean(float(p["cost"]) for p in ps) for ps in sessions.values()]
                for key, value in (("mean_session_cost", statistics.mean(costs)),
                                   ("session_min", min(costs)), ("session_max", max(costs))):
                    close(row[key], value, ident + "/" + key)
                if row["mode"] == "callback":
                    tails = [statistics.median(float(p["p99_us"]) for p in ps) for ps in sessions.values()]
                    for key, value in (("median_session_p99_us", statistics.median(tails)),
                                       ("session_p99_min_us", min(tails)),
                                       ("session_p99_max_us", max(tails)),
                                       ("observed_callback_max_us", max(float(p["observed_max_us"]) for p in ps))):
                        close(row[key], value, ident + "/" + key)

    def select(self, backend, group="primary", mode="throughput", **changes):
        expected = dict(BASE, backend=backend, mode=mode, **changes)
        rows = [r for r in self.data[group]["results"]
                if all(r[k] == str(v) for k, v in expected.items())]
        if len(rows) != 1:
            raise ValueError(f"Selection is not unique ({len(rows)}): {group} {expected}")
        row = rows[0]
        self.selected[f"{group}/{row['config_sha256']}"] = dict(
            group=group, config_sha256=row["config_sha256"], stratum=row["stratum"],
            selectors=expected)
        return row

    def pair(self, backend, group="primary", **changes):
        a = self.select(backend, group, "throughput", **changes)
        b = self.select(backend, group, "callback", **changes)
        # Observation counts and timing passes intentionally differ. All workload
        # and semantic fields, including channel/precision/output contracts, match.
        fields = tuple(BASE) + ("backend", "stratum", "host", "boundary", "operation",
                               "precision", "channels", "publication_delay_samples",
                               "playback_delay_samples", "center_offset_samples")
        if any(a[k] != b[k] for k in fields):
            raise ValueError(f"Unmatched throughput/callback pair: {backend}")
        return a, b


def generate():
    e = Evidence()
    files = {}
    macros = {}

    def macro(name, value):
        macros["PaperCmp" + name] = str(value)

    # Bind the manuscript's literal campaign-design table to checked evidence.
    coverage = e.read_json("coverage.json")
    index = e.read_json("index.json")
    expected_counts = dict(zip(GROUPS, (408, 719, 110, 46, 16)))
    for group in coverage["groups"]:
        name = group["group"]
        rows = e.data[name]["process-timings"]
        configs = {r["config_sha256"] for r in rows}
        macro(name.title().replace("-", "") + "Workloads", len(configs))
        if len(configs) != group["workloads"] or len(configs) != expected_counts[name]:
            raise ValueError("Campaign workload count mismatch")
        if len(rows) != group["processes"] or len(rows) != 9 * len(configs):
            raise ValueError("Campaign process count mismatch")
    if (index["nominal_workloads"], index["confirmation_processes"], index["pilot_processes"]) != (1299, 11691, 3945):
        raise ValueError("Manuscript campaign counts differ from original index")
    if sum(c["processes"] for c in index["campaigns"] if c["phase"] == "pilot") != index["pilot_processes"]:
        raise ValueError("Pilot process count mismatch")
    macro("Pilots", index["pilot_processes"])

    # Representative size is the middle primary size, not the best result.
    rows = []
    for backend in ANALYSIS:
        a, b = e.pair(backend)
        rows.append([LABELS[backend], interval(a, "mean_session_cost", "session_min", "session_max"),
                     interval(b, "median_session_p99_us", "session_p99_min_us", "session_p99_max_us"),
                     f"{float(b['observed_callback_max_us']):.2f}", b["publication_delay_samples"]])
    files["tables/analysis.tex"] = table(
        ["Implementation", "Cost (ns/sample)", r"p99 ($\mu$s)", r"Max. ($\mu$s)", "Delay"], rows,
        r"Scalar float analysis at the middle primary size $N=4096$, $H=1024$, "
        r"$D=64$, $f_s=48\,$kHz, one instance, no smoothing. Cost comes from the "
        r"throughput pass; p99 and maxima come from the separate callback pass. "
        r"Brackets are observed ranges of the three session means (cost) or "
        r"session medians (p99); neither is a confidence interval. Maxima retain "
        r"every observation from the nine callback processes. Delay is the "
        r"frame-endpoint-to-publication delay in samples, before callback-end visibility.",
        "tab:comparison-analysis", "lrrrr")
    for short, backend in (("Core", "core-float"), ("Vdsp", "vdsp-analysis-float"),
                           ("Hybrid", "pffft-hybrid-float")):
        a, b = e.pair(backend)
        macro(short + "Cost", f"{float(a['mean_session_cost']):.2f}")
        macro(short + "Tail", f"{float(b['median_session_p99_us']):.3f}")
    core, core_cb = e.pair("core-float")
    vdsp, vdsp_cb = e.pair("vdsp-analysis-float")
    macro("CostRatio", f"{float(core['mean_session_cost'])/float(vdsp['mean_session_cost']):.2f}")
    macro("TailRatio", f"{float(vdsp_cb['median_session_p99_us'])/float(core_cb['median_session_p99_us']):.2f}")
    macro("BudgetUs", f"{float(core_cb['callback_budget_us']):.2f}")
    macro("CoreBudgetPercent", f"{float(core_cb['p99_budget_percent']):.2f}")
    macro("VdspBudgetPercent", f"{float(vdsp_cb['p99_budget_percent']):.2f}")
    macro("DelayMs", f"{float(core['publication_delay_ms']):.2f}")
    macro("CoreHeapKiB", f"{int(core['cpp_live_heap_bytes_max'])/1024:.1f}")
    macro("VdspHeapKiB", f"{int(vdsp['cpp_live_heap_bytes_max'])/1024:.1f}")
    small_core = e.select("core-float", mode="callback", n=2048)
    macro("CoreSmallMax", f"{float(small_core['observed_callback_max_us']):.2f}")
    macro("CoreAgeMs", f"{float(core['spectrum_center_age_ms']):.2f}")
    macro("BatchAgeMs", f"{float(vdsp['spectrum_center_age_ms']):.2f}")

    # Length trends keep H, D and all other factors fixed. Error bars show the
    # complete session range, including the unfavorable hybrid variation.
    figure = [COMMENT, "\\begin{figure}[tb]\n\\centering\n"]
    styles = [("core-float", "ink", "*", "solid"),
              ("pffft-hybrid-float", "accent", "square*", "solid"),
              ("pffft-analysis-float", "black!60", "triangle*", "dashed"),
              ("fftw-analysis-float", "green!40!black", "diamond*", "dotted"),
              ("vdsp-analysis-float", "violet", "x", "dashdotted")]
    for mode, value, low, high, ylabel in (
            ("throughput", "mean_session_cost", "session_min", "session_max", "Cost (ns/sample)"),
            ("callback", "median_session_p99_us", "session_p99_min_us", "session_p99_max_us", r"Callback p99 ($\mu$s)")):
        figure.append(r"\begin{tikzpicture}\begin{axis}[width=0.48\linewidth,height=5.3cm," + "\n"
                      + r"xmode=log,log basis x=2,ymode=log,xmin=1800,xmax=19000,"
                      + r"xtick={2048,4096,16384},xticklabels={2048,4096,16384},"
                      + "\n" + r"xlabel={$N$},ylabel={" + ylabel + r"},grid=major,"
                      + r"tick label style={font=\scriptsize},label style={font=\small},"
                      + "\n" + r"legend style={font=\scriptsize,draw=none,at={(0.5,1.03)},anchor=south},legend columns=2]" + "\n")
        for backend, color, marker, line in styles:
            coords = []
            for n in (2048, 4096, 16384):
                r = e.select(backend, mode=mode, n=n)
                y = float(r[value])
                coords.append(f"({n},{y:.12g}) += (0,{float(r[high])-y:.12g}) -= (0,{y-float(r[low]):.12g})")
            figure.append(r"\addplot+[color=" + color + ",mark=" + marker + "," + line
                          + r",error bars/.cd,y dir=both,y explicit] coordinates {"
                          + " ".join(coords) + "};\n")
            if mode == "throughput":
                figure.append(r"\addlegendentry{" + LABELS[backend] + "}\n")
        figure.append("\\end{axis}\\end{tikzpicture}\n")
    figure.append(r"\caption{Primary scalar float length trends at $H=1024$, $D=64$, "
                  r"48\,kHz, without smoothing. Each point uses three sessions of "
                  r"three processes; bars show their full descriptive session range "
                  r"under the definitions of Table~\ref{tab:comparison-analysis}. "
                  r"The logarithmic axes distinguish aggregate work from callback "
                  r"concentration. No unfavorable process or session is removed.}" + "\n"
                  + "\\label{fig:comparison-length}\n\\end{figure}\n")
    files["figures/length.tex"] = "".join(figure)

    # Full identity and FIR chains remain separate, despite similar costs.
    rows = []
    for operation, prefix in (("Inverse job", "inverse"), ("Identity chain", "identity"), ("FIR chain", "fir")):
        names = (["inverse-stream-batch-float", "inverse-stream-incremental-float", "pffft-inverse-float", "fftw-inverse-float", "vdsp-inverse-float"]
                 if prefix == "inverse" else [f"ols-{prefix}-batch-float", f"ols-{prefix}-incremental-float", f"pffft-ols-{prefix}-float", f"fftw-ols-{prefix}-float", f"vdsp-ols-{prefix}-float"])
        for index, (name, label) in enumerate(zip(names, ["Batch control", "Incremental control", "PFFFT", "FFTW", "vDSP"])):
            a, b = e.pair(name)
            delay = a["publication_delay_samples"] if prefix == "inverse" else a["playback_delay_samples"]
            rows.append([operation if index == 0 else "", label,
                         interval(a, "mean_session_cost", "session_min", "session_max"),
                         interval(b, "median_session_p99_us", "session_p99_min_us", "session_p99_max_us"), delay])
    files["tables/synthesis.tex"] = table(
        ["Workload", "Implementation", "Cost (ns/sample)", r"p99 ($\mu$s)", "Delay"], rows,
        r"Periodic inverse jobs and complete overlap-save chains, with the same "
        r"$N,H,D,f_s$, precision and instance count as Table~\ref{tab:comparison-analysis}. "
        r"Session summaries use the same definitions. Delay is release-to-publication "
        r"for inverse jobs and input-to-delivery for chains (samples). The incremental "
        r"controls distribute butterflies but retain bulk buffering and copy stages; they "
        r"do not inherit the production analyzer's whole-pipeline quota bound. "
        r"The identity and three-tap FIR are functional fixtures, not efficient "
        r"application choices for FFT convolution.", "tab:comparison-synthesis", "llrrr")
    # Isolated kernels use a different denominator and are never mixed with the
    # streaming costs in this or any other table.
    for short, backend in (("ScalarIfft", "ifft-float"), ("VdspIfft", "vdsp-ifft-float")):
        r = e.select(backend, mode="complete")
        macro(short + "Us", f"{float(r['mean_session_cost'])/1000:.2f}")

    # All designated one-factor stress cases and phase choices are retained.
    rows = []
    cases = [
        ("Reference", "primary", dict(n=2048)),
        ("Smoothing", "primary", dict(n=2048, smooth=1)),
        ("Shorter hop", "extensions", dict(n=2048, hop=257)),
        ("Live cache/settings", "extensions", dict(n=2048, hop=257, state="live", smooth=1)),
        ("Startup", "extensions", dict(n=2048, state="startup")),
        (r"96\,kHz", "extensions", dict(n=2048, rate=96000)),
        ("Background load 64", "extensions", dict(n=2048, load=64)),
        ("32 MiB cache touch", "extensions", dict(n=2048, cache_mib=32)),
        ("Callback offset 1", "extensions", dict(n=2048, callback_offset=1)),
        ("Callback offset 15", "extensions", dict(n=2048, callback_offset=15)),
        ("Callback offset 63", "extensions", dict(n=2048, callback_offset=63)),
        ("4 aligned instances", "extensions", dict(n=2048, count=4)),
        ("4 staggered instances", "extensions", dict(n=2048, count=4, alignment="staggered")),
        ("16 aligned instances", "extensions", dict(n=2048, count=16)),
        ("16 staggered instances", "extensions", dict(n=2048, count=16, alignment="staggered")),
        (r"$N=128$, $H=37$", "short-hop", dict(n=128, hop=37)),
    ]
    for label, group, changes in cases:
        cells = [label]
        for backend in ("core-float", "pffft-hybrid-float", "vdsp-analysis-float"):
            r = e.select(backend, group, "callback", **changes)
            cells.append(interval(r, "median_session_p99_us", "session_p99_min_us", "session_p99_max_us"))
        rows.append(cells)
    files["tables/extensions.tex"] = table(
        ["Configuration", "Production core", "PFFFT hybrid", "vDSP native"], rows,
        r"Sensitivity of callback p99 in microseconds (session range in brackets). "
        r"Defaults are scalar float, $N=2048$, $H=1024$, $D=64$, 48\,kHz, "
        r"one aligned instance, no smoothing/load/cache touch, zero callback offset. "
        r"Only the named factors change. Shorter-hop and live-cache rows use "
        r"$H=257$; the latter also enables smoothing. Rows are separate matched comparisons; their "
        r"different durations and observation counts are not pooled. Background "
        r"load 64 is a cascade of 64 binary64 DC blockers, included in timed work; "
        r"cache touching occurs outside timing. "
        r"The three displayed implementations span fully distributed, hybrid and "
        r"native execution; the complete evidence retains the remaining backends.",
        "tab:comparison-extensions", "lrrr")

    rows = []
    for backend, label in (("core-independent4-float", "Four scalar cores"),
                           ("core-independent4-simd", "Four-lane SIMD core"),
                           ("pffft-analysis4-float", "Four PFFFT analyses"),
                           ("fftw-analysis4-float", "Four FFTW analyses"),
                           ("vdsp-analysis4-float", "Four vDSP analyses"),
                           ("core-double", "Scalar double core"),
                           ("fftw-analysis-double", "Scalar double FFTW"),
                           ("vdsp-analysis-double", "Scalar double vDSP")):
        a, b = e.pair(backend, "extensions")
        rows.append([label, interval(a, "mean_session_cost", "session_min", "session_max"),
                     interval(b, "median_session_p99_us", "session_p99_min_us", "session_p99_max_us")])
    files["tables/channels.tex"] = table(
        ["Configuration", "Cost (ns/engine sample)", r"p99 ($\mu$s)"], rows,
        r"Independent-channel and precision comparisons at $N=4096$, $H=1024$, "
        r"$D=64$, 48\,kHz without smoothing. The first five rows include four "
        r"independent float channels in every engine sample; the last three "
        r"contain one double channel. Each block is comparable internally, "
        r"not across channel counts. Double adapters receive the common rounded "
        r"float input samples and window coefficients promoted separately, with "
        r"their product evaluated in double.", "tab:comparison-channels", "lrr")

    transitions = {name: e.read("transitions", "transitions-" + name)
                   for name in ("responses", "callback-costs", "publications")}
    if {r["rate"] for r in transitions["responses"]} != {"48000"}:
        raise ValueError("Unexpected transition sample rate")
    rows = []
    for backend, label in (("core-float", "Production float"), ("core-double", "Production double"),
                           ("pffft-hybrid-float", "PFFFT hybrid"),
                           ("pffft-scheduled-batch-float", "PFFFT scheduled batch")):
        rs = [r for r in transitions["responses"] if r["backend"] == backend and r["horizon_samples"] == "65536" and r["control"] == "False"]
        if Counter(r["outcome"] for r in rs) != {"published": 81, "replaced": 9, "pending-no-response": 9}:
            raise ValueError("Unexpected transition response outcomes")
        per_control = []
        for control in ("True", "False"):
            cs = [r for r in transitions["callback-costs"] if r["backend"] == backend and r["horizon_samples"] == "65536" and r["control"] == control]
            per_control.append(f"{max(float(r['observed_max_us']) for r in cs):.2f}")
        rows.append([label, f"{max(float(r['first_publication_latency_ms']) for r in rs if r['first_publication_latency_ms']):.2f}", *per_control])
    files["tables/transitions.tex"] = table(
        ["Implementation", "Response (ms)", r"Control max. ($\mu$s)", r"Change max. ($\mu$s)"], rows,
        r"Interactive transition suite with initial $N=2048$, $H=1024$, "
        r"$D=64$, $f_s=48\,$kHz and 65,536-sample horizon. Response is the largest "
        r"request-to-first-publication delay among responding requests, not "
        r"the stationary frame age. Control/change columns retain the largest "
        r"callback in any event window and any of nine processes, without "
        r"pooling or subtraction. Every process has nine published requests, "
        r"one replaced request and one pending request at the finite horizon. "
        r"The separate short-hop transition suite is retained in the evidence; "
        r"window overlaps and small counts preclude a rare-event tail estimate.",
        "tab:comparison-transitions", "lrrr")

    # Analysis coverage records every reported bin and preserves pointwise
    # diagnostics. Inverse/chain audits have their own absolute-error contracts.
    audits = [r for g in GROUPS for r in e.data[g]["accuracy-coverage"]]
    rows = []
    for precision in ("float", "double"):
        rs = [r for r in audits if r["precision"] == precision]
        for r in rs:
            if r["expected_spectra"] != r["checked_spectra"] or r["expected_bins"] != r["checked_bins"]:
                raise ValueError("Incomplete stationary analysis coverage")
        values = [max(float(r[key]) for r in rs) for key in ("max_relative_l2", "max_relative_linf")]
        limit = 3e-4 if precision == "float" else 1e-10
        if max(values) > limit:
            raise ValueError("Analysis norm exceeds its frozen acceptance budget")
        count = sum(int(r["checked_spectra"]) for r in rs)
        diagnostic = sum(int(r["legacy_pointwise_failures"]) for r in rs)
        rows.append([precision, f"{count:,}", sci(values[0]), sci(values[1]), f"{diagnostic:,}"])
        macro(precision.title() + "Ltwo", sci(values[0])[1:-1])
        macro(precision.title() + "Linf", sci(values[1])[1:-1])
    files["tables/numerical.tex"] = table(
        ["Precision", "Audited spectra", r"Maximum relative $\ell_2$", r"Maximum relative $\ell_\infty$", "Diagnostics"], rows,
        r"Stationary analysis audit totals and largest observed per-vector "
        r"normwise errors over all four stationary groups, passes, sessions, "
        r"processes, instances and channels. These repeated vector checks are "
        r"coverage counts, not independent statistical replicates. Diagnostics "
        r"count violations of the retained legacy pointwise rule; that rule is "
        r"not the frozen spectrum-norm acceptance test. Zero-reference vectors "
        r"are checked separately. Inverse and chain absolute-error checks have "
        r"different output units and are not mixed into these norms.",
        "tab:comparison-numerical", "lrrrr")
    for precision in ("float", "double"):
        for boundary, short in (("inverse-job", "Inverse"), ("chain", "Chain")):
            rs = [r for g in GROUPS for r in e.data[g]["results"]
                  if r["precision"] == precision and r["boundary"] == boundary]
            error = max(float(r["max_abs_error"]) for r in rs)
            macro(precision.title() + short + "Abs", sci(error)[1:-1])
    for precision in ("float", "double"):
        rs = [r for r in transitions["publications"] if r["precision"] == precision]
        for r in rs:
            if max(float(r["max_relative_l2"]), float(r["max_relative_linf"])) > float(r["tolerance"]):
                raise ValueError("Transition numerical acceptance failed")
        macro(precision.title() + "TransitionLinf", sci(max(float(r["max_relative_linf"]) for r in rs))[1:-1])
    single = e.select("core-float", "single-sample", "callback", n=2048, block=1)
    macro("SingleTail", f"{float(single['median_session_p99_us']):.3f}")
    macro("SingleCoreMax", f"{float(single['observed_callback_max_us']):.2f}")
    batch_single = e.select("vdsp-analysis-float", "single-sample", "callback", n=2048, block=1)
    close(batch_single["median_session_p99_us"], single["median_session_p99_us"], "single-sample p99 equality")
    single_processes = [r for r in e.data["single-sample"]["process-timings"]
                        if r["config_sha256"] == single["config_sha256"]]
    macro("SingleTimer", f"{statistics.median(float(r['timer_p99_us']) for r in single_processes):.3f}")
    macro("SingleVdspMax", f"{float(batch_single['observed_callback_max_us']):.2f}")
    hybrid_large = e.select("pffft-hybrid-float", n=16384)
    macro("HybridLargeLow", f"{float(hybrid_large['session_min']):.2f}")
    macro("HybridLargeHigh", f"{float(hybrid_large['session_max']):.2f}")
    macro("Workloads", sum(len({r["config_sha256"] for r in e.data[g]["process-timings"]}) for g in GROUPS))
    macro("Processes", sum(len(e.data[g]["process-timings"]) for g in GROUPS))
    macro("TransitionPublications", len(transitions["publications"]))
    files["macros.tex"] = COMMENT + "".join("\\newcommand{\\" + k + "}{" + v + "}\n" for k, v in sorted(macros.items()))
    receipt = dict(schema=1, generator="tools/comparison_paper.py",
                   generator_sha256=digest(Path(__file__).read_bytes()),
                   inputs=e.inputs, selections=list(e.selected.values()),
                   derivation="Three process means per session; equally weighted session means. Process p99 medians per session, then median of session medians. No pooled observations, timer subtraction or outlier removal. CSV identities checked against immutable handoff manifest; raw callbacks are not re-read by this editorial generator.",
                   outputs={name: digest(text.encode()) for name, text in sorted(files.items())})
    files["receipt.json"] = json.dumps(receipt, indent=2, sort_keys=True) + "\n"
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify byte-for-byte regeneration without writing")
    args = parser.parse_args()
    files = generate()
    if args.check:
        for name, content in files.items():
            path = OUTPUT / name
            if not path.is_file() or path.read_bytes() != content.encode():
                raise SystemExit(f"Stale paper result asset: {path}")
        actual = {str(p.relative_to(OUTPUT)) for p in OUTPUT.rglob("*") if p.is_file()}
        if actual != set(files):
            raise SystemExit("Unexpected files in generated/paper-comparison")
        print(f"Verified {len(files)} editorial assets and all stationary hierarchical summaries")
    else:
        for name, content in files.items():
            path = OUTPUT / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        print(f"Wrote {len(files)} editorial assets to {OUTPUT}")


if __name__ == "__main__":
    main()
