"""Generate teaching-figure data for periodic analysis windows (stdlib only).

Run from any directory. The coefficients match src/dsp/window.hpp.
This computes an ideal window response, not captured Rack output. A tone at
half a bin makes leakage and sampled peak-height differences visible.
"""

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LENGTH = 2048
COEFFICIENTS = {
    'Boxcar': (1.0,),
    'Hann': (0.5, -0.5),
    'Flattop': (0.21557895, -0.416631580, 0.277263158,
                -0.083578947, 0.006947368),
}


def response(window, offset):
    """Coherent-gain-normalized magnitude in dB at a fractional bin offset."""
    real = sum(w * math.cos(2 * math.pi * offset * n / LENGTH)
               for n, w in enumerate(window))
    imag = sum(w * math.sin(2 * math.pi * offset * n / LENGTH)
               for n, w in enumerate(window))
    return 20 * math.log10(max(math.hypot(real, imag) / sum(window), 1e-12))


def main():
    lines = ['% Generated by scripts/generate_window_figure.py; do not edit.',
             '% N=2048, periodic windows, tone at +0.5 bin, common -60..0 dB axes.']
    for name, coefficients in COEFFICIENTS.items():
        window = [sum(c * math.cos(2 * math.pi * k * n / LENGTH)
                      for k, c in enumerate(coefficients))
                  for n in range(LENGTH)]
        points = []
        for i in range(481):
            x = -6 + i / 40
            db = max(-60, min(0, response(window, x - 0.5)))
            points.append(f'({x:.3f},{db:.3f})')
        lines.append('\\def\\Window' + name + 'Curve{' + '\n'.join(points) + '}')
        dots = []
        for x in range(-6, 7):
            db = response(window, x - 0.5)
            if db >= -60:
                dots.append(f'\\fill[panelAccent] ({x},{min(0, db):.3f}) circle[radius=1.3pt];')
        lines.append('\\def\\Window' + name + 'Dots{' + '\n'.join(dots) + '}')
        print(f'{name}: halfway-bin peak {response(window, 0.5):.3f} dB')
    (ROOT / 'docs/figures/WindowResponseData.tex').write_text('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
